<a href="https://colab.research.google.com/github/mchhour31/NN_work/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [120]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [121]:
tf.__version__

'2.9.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [122]:
df = pd.read_csv("Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [123]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [124]:
X.shape

(10000, 10)

In [125]:
y.shape

(10000,)

### Encoding categorical data

Label Encoding the "Gender" column

In [126]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [127]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

One Hot Encoding the "Geography" column

In [128]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers=[
    ('encoder', OneHotEncoder(handle_unknown='ignore'), [1])], remainder='passthrough')

X = np.array(ct.fit_transform(X))

In [129]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [130]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

### Feature Scaling

In [131]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [132]:
from tensorflow import keras

ann = keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [133]:
ann.add(keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [134]:
ann.add(keras.layers.Dense(units=1, activation='relu'))

### Adding the output layer

In [135]:
ann.add(keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [136]:
ann.compile(optimizer='adam',
            loss='binary_crossentropy',
            metrics=['accuracy'])

### Training the ANN on the Training set

In [137]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6187 - accuracy: 0.7922
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5012 - accuracy: 0.7922
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4504 - accuracy: 0.7922
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4389 - accuracy: 0.7922
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4351 - accuracy: 0.7922
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4326 - accuracy: 0.7922
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4310 - accuracy: 0.7922
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4290 - accuracy: 0.7922
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4264 - accuracy: 0.7922
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4232 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [138]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 109ms/step


array([[0.0272181]], dtype=float32)

Therefore, the ANN predicts that the customer will stay in the bank

### Predicting the Test set results

In [141]:
from sklearn.metrics import confusion_matrix, accuracy_score

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

cm = confusion_matrix(y_test, y_pred)

print(cm, accuracy_score(y_test, y_pred))

63/63 [==============================] - 0s 1ms/step
[[1546   79]
 [ 184  191]] 0.8685
