<a href="https://colab.research.google.com/github/mchhour31/NN_work/blob/main/data_preprocessing_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Template

## Importing the libraries

In [97]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [98]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values # [Country, Age, Salary]
y = dataset.iloc[:, -1].values # [Purchased]
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Data Imputation

In [99]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean') # mean imputation
imp.fit(x[:, 1:3])
x[:, 1:3] = np.round(imp.transform(x[:, 1:3]), decimals=2)

# Encoding categorical data

### Encoding the independent variable

In [100]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer # used for transforming columns

transformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(transformer.fit_transform(x))
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.78],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.78, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

### Encoding dependent variable

In [103]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Splitting the dataset into the Training set and Test set

In [131]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state=2) # 80:20 split -- via random sampling, but its fine cuz class-balanced dataset

## Feature Scaling

In [138]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
train_x = sc.fit_transform(train_x) 
test_x = sc.transform(test_x)

In [139]:
train_x

array([[ 1.        , -0.57735027, -0.57735027, -0.8067266 , -0.72132045],
       [ 1.        , -0.57735027, -0.57735027,  0.61760678,  0.58171004],
       [ 1.        , -0.57735027, -0.57735027,  1.25064383,  1.23322529],
       [-1.        ,  1.73205081, -0.57735027, -1.59802292, -1.09361488],
       [-1.        , -0.57735027,  1.73205081, -0.33194881, -0.44209963],
       [-1.        , -0.57735027,  1.73205081, -0.20850658, -1.27976209],
       [ 1.        , -0.57735027, -0.57735027, -0.49020807,  0.11634201],
       [-1.        ,  1.73205081, -0.57735027,  1.56716236,  1.60551972]])

In [140]:
test_x

array([[-1.        ,  1.73205081, -0.57735027,  1.        ,  1.        ],
       [-1.        , -0.57735027,  1.73205081, -1.        , -1.        ]])